service:
  dm_api_account: 'http://5.63.153.31:5051'
  mailhog: 'http://5.63.153.31:5025'

user:
  login: 'tst_account_8310'
  password: 'strongpassword'

telegram:
  token: '7594853684:AAFntGcFr8Y6EKIIIhn_yQILj-r9qZSIALM'
  chat_id: '-1002633192883'
