name: Python Tests
on: [ push, pull_request ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    name: Python tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Correct version for checking out the code
      - name: Set up Python
        uses: actions/setup-python@v4  # Correct version for setting up Python
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest ./tests --alluredir=allure-results --disable-warnings
        continue-on-error: true

      - name: Archive allure results
        uses: actions/upload-artifact@v4  # Correct version for uploading artifacts
        with:
          name: allure-results
          path: allure-results
          retention-days: 1

  generate-report:
    runs-on: ubuntu-latest
    needs: test
    name: Generate report
    steps:
      - uses: actions/setup-java@v4  # Correct version for setting up Java
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Install Allure
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.32.0/allure-2.32.0.tgz
          sudo tar -xzvf allure-2.32.0.tgz -C /opt/
          sudo ln -s /opt/allure-2.32.0/bin/allure /usr/bin/allure
      - name: Download allure results
        uses: actions/download-artifact@v4  # Correct version for downloading artifacts
      - run: allure generate -c ./allure-results -o _site
      - name: Store report
        uses: actions/upload-artifact@v4  # Correct version for uploading artifacts
        with:
          name: _site
          path: _site
          retention-days: 1

  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    name: Publish report
    steps:
      - uses: actions/checkout@v4  # Ensure using the latest version for checking out the code

      - name: Download site report
        uses: actions/download-artifact@v4  # Correct version for downloading artifacts

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3  # Correct version for uploading pages artifacts (v3 is valid)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4  # Correct version for deploying to GitHub Pages

      - run: echo "https://Uroboric.github.io/dm_api_tests/"